/**
 * Emits the generated Angular swagger client implementation.
 *
 * @returns The TypeScript source for the Angular client file.
 */
export interface EmitAngularClientOptions {
  endpointsImportPath?: string;
}

export function emitAngularClient(options: EmitAngularClientOptions = {}): string {
  const endpointsImportPath = options.endpointsImportPath ?? "./api-endpoints";

  return String.raw`
/* eslint-disable */
// This file was generated by @let-aurn/swagger-client.
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { EnvironmentProviders, Inject, Injectable, InjectionToken, makeEnvironmentProviders, Type } from '@angular/core';
import { Observable } from 'rxjs';
import type {
  AnyApiEndpoint,
  BodyVariablesOf,
  HeaderVariablesOf,
  PathVariablesOf,
  QueryVariablesOf,
  ResponseOf
} from '${endpointsImportPath}';

/**
 * Configures the generated Angular swagger client.
 */
export interface SwaggerClientConfig {
  baseUrl: string;
  httpClient?: Type<SwaggerHttpClient>;
}

/**
 * Describes an HTTP request produced by the generated swagger client.
 */
export interface SwaggerHttpRequest {
  method: string;
  url: string;
  headers?: Record<string, string>;
  query?: Record<string, unknown>;
  body?: unknown;
}

/**
 * Defines the HTTP adapter contract used by the generated Angular swagger client.
 */
export interface SwaggerHttpClient {
  /**
   * Executes an HTTP request and returns the typed response stream.
   *
   * @param request The normalized swagger HTTP request.
   * @returns An observable of the typed response body.
   */
  request<T>(request: SwaggerHttpRequest): Observable<T>;
}

/**
 * Resolves the request variable object accepted by a generated endpoint.
 */
export type SwaggerRequestVariables<TEndpoint extends AnyApiEndpoint> =
  OptionalProperty<'pathVariables', PathVariablesOf<TEndpoint>> &
  OptionalProperty<'queryVariables', QueryVariablesOf<TEndpoint>> &
  OptionalProperty<'headerVariables', HeaderVariablesOf<TEndpoint>> &
  OptionalProperty<'bodyVariables', BodyVariablesOf<TEndpoint>>;

type OptionalProperty<TKey extends string, TValue> = IsEmptyVariables<TValue> extends true
  ? { [K in TKey]?: never }
  : undefined extends TValue
    ? { [K in TKey]?: TValue }
    : { [K in TKey]: TValue };

type IsEmptyVariables<TValue> = keyof TValue extends never
  ? true
  : TValue extends Record<string, never>
    ? true
    : false;

export const SWAGGER_CLIENT_CONFIG = new InjectionToken<SwaggerClientConfig>('SWAGGER_CLIENT_CONFIG');
export const SWAGGER_HTTP_CLIENT = new InjectionToken<SwaggerHttpClient>('SWAGGER_HTTP_CLIENT');

/**
 * Adapts Angular HttpClient to the generated swagger HTTP adapter contract.
 */
@Injectable()
export class AngularSwaggerHttpClient implements SwaggerHttpClient {
  /**
   * Creates the default Angular HTTP adapter.
   *
   * @param http The Angular HttpClient used to execute requests.
   */
  constructor(private readonly http: HttpClient) {}

  /**
   * Executes a normalized swagger request with Angular HttpClient.
   *
   * @param request The normalized swagger HTTP request.
   * @returns An observable of the typed response body.
   */
  request<T>(request: SwaggerHttpRequest): Observable<T> {
    return this.http.request<T>(request.method, request.url, {
      body: request.body,
      headers: new HttpHeaders(request.headers ?? {}),
      params: toHttpParams(request.query)
    });
  }
}

/**
 * Sends typed requests to generated API endpoint definitions.
 */
@Injectable()
export class SwaggerClientService {
  /**
   * Creates the generated swagger client service.
   *
   * @param config The swagger client runtime configuration.
   * @param http The HTTP adapter used to execute requests.
   */
  constructor(
    @Inject(SWAGGER_CLIENT_CONFIG) private readonly config: SwaggerClientConfig,
    @Inject(SWAGGER_HTTP_CLIENT) private readonly http: SwaggerHttpClient
  ) {}

  /**
   * Sends a typed request for a generated API endpoint.
   *
   * @param endpoint The generated endpoint definition to call.
   * @param variables The path, query, header, and body variables for the endpoint.
   * @returns An observable of the endpoint response type.
   */
  request<TEndpoint extends AnyApiEndpoint>(
    endpoint: TEndpoint,
    variables?: SwaggerRequestVariables<TEndpoint>
  ): Observable<ResponseOf<TEndpoint>> {
    return this.http.request<ResponseOf<TEndpoint>>(buildRequest(this.config.baseUrl, endpoint, variables));
  }
}

/**
 * Provides the generated Angular swagger client and its HTTP adapter in an environment injector.
 *
 * @param config The swagger client runtime configuration.
 * @returns Environment providers for application or route configuration.
 */
export function provideSwaggerClient(config: SwaggerClientConfig): EnvironmentProviders {
  return makeEnvironmentProviders([
    { provide: SWAGGER_CLIENT_CONFIG, useValue: config },
    { provide: SWAGGER_HTTP_CLIENT, useClass: config.httpClient ?? AngularSwaggerHttpClient },
    SwaggerClientService
  ]);
}

function buildRequest<TEndpoint extends AnyApiEndpoint>(
  baseUrl: string,
  endpoint: TEndpoint,
  variables?: SwaggerRequestVariables<TEndpoint>
): SwaggerHttpRequest {
  const pathVariables = variables?.pathVariables as Record<string, unknown> | undefined;
  const queryVariables = variables?.queryVariables as Record<string, unknown> | undefined;
  const headerVariables = variables?.headerVariables as Record<string, unknown> | undefined;
  const bodyVariables = variables?.bodyVariables;
  const path = endpoint.path.replace(/\{([^}]+)\}/g, (_, key: string) => {
    const value = pathVariables?.[key];

    if (value === undefined || value === null) {
      throw new Error('Missing path variable "' + key + '" for endpoint "' + endpoint.name + '".');
    }

    return encodeURIComponent(String(value));
  });

  return {
    method: endpoint.method,
    url: joinUrl(baseUrl, path),
    headers: stringifyRecord(headerVariables),
    query: queryVariables,
    body: bodyVariables
  };
}

function toHttpParams(query: Record<string, unknown> | undefined): HttpParams {
  let params = new HttpParams();

  for (const [key, value] of Object.entries(query ?? {})) {
    if (value === undefined || value === null) {
      continue;
    }

    if (Array.isArray(value)) {
      for (const item of value) {
        params = params.append(key, String(item));
      }
    } else {
      params = params.set(key, String(value));
    }
  }

  return params;
}

function stringifyRecord(record: Record<string, unknown> | undefined): Record<string, string> | undefined {
  if (!record) {
    return undefined;
  }

  return Object.fromEntries(
    Object.entries(record)
      .filter(([, value]) => value !== undefined && value !== null)
      .map(([key, value]) => [key, String(value)])
  );
}

function joinUrl(baseUrl: string, path: string): string {
  return baseUrl.replace(/\/+$/, '') + '/' + path.replace(/^\/+/, '');
}
`;
}
