import type { EndpointModel, ProjectModel, VariableModel } from "../core/types.js";
import { quote } from "../core/names.js";

/**
 * Emits the generated typed API endpoint definition file.
 *
 * @param project The normalized OpenAPI project model.
 * @returns The TypeScript source for api-endpoints.ts.
 */
export interface EmitEndpointsOptions {
  modelsImportPath?: string;
}

export function emitEndpoints(project: ProjectModel, options: EmitEndpointsOptions = {}): string {
  const modelsImportPath = options.modelsImportPath ?? "./api-models";
  const modelNames = new Set(project.schemas.map((schema) => schema.name));
  const lines = [
    "/* eslint-disable */",
    "// This file was generated by @let-aurn/swagger-client.",
    `import type * as ApiModels from '${modelsImportPath}';`,
    "",
    "/**",
    " * Represents the HTTP methods supported by generated endpoints.",
    " */",
    "export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';",
    "",
    "/**",
    " * Describes a generated API endpoint and carries its request and response types.",
    " */",
    "export interface ApiEndpointDefinition<TPathVariables, TQueryVariables, THeaderVariables, TBody, TResponse> {",
    "  readonly name: string;",
    "  readonly method: HttpMethod;",
    "  readonly path: string;",
    "  readonly operationId: string;",
    "  readonly sourceFile: string;",
    "  readonly pathVariables: readonly ApiVariableDefinition[];",
    "  readonly queryVariables: readonly ApiVariableDefinition[];",
    "  readonly headerVariables: readonly ApiVariableDefinition[];",
    "  readonly __types?: {",
    "    readonly pathVariables: TPathVariables;",
    "    readonly queryVariables: TQueryVariables;",
    "    readonly headerVariables: THeaderVariables;",
    "    readonly bodyVariables: TBody;",
    "    readonly response: TResponse;",
    "  };",
    "}",
    "",
    "/**",
    " * Describes a request variable using its exact OpenAPI parameter name.",
    " */",
    "export interface ApiVariableDefinition {",
    "  readonly name: string;",
    "  readonly required: boolean;",
    "}",
    "",
    "/**",
    " * Creates a typed endpoint definition while preserving phantom request and response types.",
    " *",
    " * @param endpoint The serializable endpoint metadata.",
    " * @returns The endpoint metadata with request and response type information.",
    " */",
    "function defineEndpoint<TPathVariables, TQueryVariables, THeaderVariables, TBody, TResponse>(",
    "  endpoint: Omit<ApiEndpointDefinition<TPathVariables, TQueryVariables, THeaderVariables, TBody, TResponse>, '__types'>",
    "): ApiEndpointDefinition<TPathVariables, TQueryVariables, THeaderVariables, TBody, TResponse> {",
    "  return endpoint as ApiEndpointDefinition<TPathVariables, TQueryVariables, THeaderVariables, TBody, TResponse>;",
    "}",
    "",
    "/**",
    " * Represents any generated API endpoint.",
    " */",
    "export type AnyApiEndpoint = ApiEndpointDefinition<any, any, any, any, any>;",
    "/**",
    " * Extracts the path variable type from a generated endpoint.",
    " */",
    "export type PathVariablesOf<TEndpoint extends AnyApiEndpoint> = NonNullable<TEndpoint['__types']>['pathVariables'];",
    "/**",
    " * Extracts the query variable type from a generated endpoint.",
    " */",
    "export type QueryVariablesOf<TEndpoint extends AnyApiEndpoint> = NonNullable<TEndpoint['__types']>['queryVariables'];",
    "/**",
    " * Extracts the header variable type from a generated endpoint.",
    " */",
    "export type HeaderVariablesOf<TEndpoint extends AnyApiEndpoint> = NonNullable<TEndpoint['__types']>['headerVariables'];",
    "/**",
    " * Extracts the body variable type from a generated endpoint.",
    " */",
    "export type BodyVariablesOf<TEndpoint extends AnyApiEndpoint> = NonNullable<TEndpoint['__types']>['bodyVariables'];",
    "/**",
    " * Extracts the response type from a generated endpoint.",
    " */",
    "export type ResponseOf<TEndpoint extends AnyApiEndpoint> = NonNullable<TEndpoint['__types']>['response'];",
    "",
    "type EmptyObject = Record<string, never>;",
    "",
    "/**",
    " * Contains all generated API endpoint definitions.",
    " */",
    "export namespace ApiEndpoints {"
  ];

  for (const endpoint of project.endpoints) {
    lines.push(emitEndpoint(endpoint, modelNames));
  }

  lines.push("}", "");
  return lines.join("\n");
}

function emitEndpoint(endpoint: EndpointModel, modelNames: Set<string>): string {
  const pathType = variablesObjectType(endpoint.pathVariables, modelNames);
  const queryType = variablesObjectType(endpoint.queryVariables, modelNames);
  const headerType = variablesObjectType(endpoint.headerVariables, modelNames);
  const bodyType = endpoint.bodyType ? qualifyModelTypes(endpoint.bodyType, modelNames) : "void";
  const responseType = qualifyModelTypes(endpoint.responseType, modelNames);

  return [
    "  /**",
    `   * Defines the ${endpoint.operationId} API endpoint.`,
    "   */",
    `  export const ${endpoint.name} = defineEndpoint<${pathType}, ${queryType}, ${headerType}, ${bodyType}, ${responseType}>({`,
    `    name: ${quote(endpoint.name)},`,
    `    method: ${quote(endpoint.method)},`,
    `    path: ${quote(endpoint.path)},`,
    `    operationId: ${quote(endpoint.operationId)},`,
    `    sourceFile: ${quote(endpoint.sourceFile)},`,
    `    pathVariables: ${variablesMetadata(endpoint.pathVariables)},`,
    `    queryVariables: ${variablesMetadata(endpoint.queryVariables)},`,
    `    headerVariables: ${variablesMetadata(endpoint.headerVariables)}`,
    "  });"
  ].join("\n");
}

function variablesMetadata(variables: VariableModel[]): string {
  if (variables.length === 0) {
    return "[]";
  }

  const entries = variables.map((variable) => {
    return `{ name: ${quote(variable.name)}, required: ${String(variable.required)} }`;
  });

  return `[${entries.join(", ")}]`;
}

function variablesObjectType(variables: VariableModel[], modelNames = new Set<string>()): string {
  if (variables.length === 0) {
    return "EmptyObject";
  }

  const props = variables.map((variable) => {
    const optional = variable.required ? "" : "?";
    return `${propertyKey(variable.name)}${optional}: ${qualifyModelTypes(variable.type, modelNames)}`;
  });

  return `{ ${props.join("; ")} }`;
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quote(name);
}

function qualifyModelTypes(type: string, modelNames: Set<string>): string {
  return type.replace(/\b[A-Z][A-Za-z0-9_]*\b/g, (name) => {
    return modelNames.has(name) ? `ApiModels.${name}` : name;
  });
}
