import { emitSchemaInterface } from "../core/schema-to-typescript.js";
import type { ProjectModel } from "../core/types.js";

/**
 * Emits the generated TypeScript API model file.
 *
 * @param project The normalized OpenAPI project model.
 * @returns The TypeScript source for api-models.ts.
 */
export function emitModels(project: ProjectModel): string {
  const lines = [
    "/* eslint-disable */",
    "// This file was generated by @let-aurn/swagger-client.",
    ""
  ];

  for (const schema of project.schemas) {
    lines.push(emitSchemaInterface(schema.name, schema.schema), "");
  }

  return lines.join("\n");
}
