/**
 * Emits the generated React swagger client implementation.
 *
 * @returns The TypeScript source for the React client file.
 */
export interface EmitReactClientOptions {
  endpointsImportPath?: string;
}

export function emitReactClient(options: EmitReactClientOptions = {}): string {
  const endpointsImportPath = options.endpointsImportPath ?? "./api-endpoints";

  return String.raw`
/* eslint-disable */
// This file was generated by @let-aurn/swagger-client.
import { useMemo } from 'react';
import type {
  AnyApiEndpoint,
  BodyVariablesOf,
  HeaderVariablesOf,
  PathVariablesOf,
  QueryVariablesOf,
  ResponseOf
} from '${endpointsImportPath}';

/**
 * Configures the generated React swagger client.
 */
export interface SwaggerClientConfig {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  headers?: Record<string, string>;
}

/**
 * Resolves the request variable object accepted by a generated endpoint.
 */
export type SwaggerRequestVariables<TEndpoint extends AnyApiEndpoint> =
  OptionalProperty<'pathVariables', PathVariablesOf<TEndpoint>> &
  OptionalProperty<'queryVariables', QueryVariablesOf<TEndpoint>> &
  OptionalProperty<'headerVariables', HeaderVariablesOf<TEndpoint>> &
  OptionalProperty<'bodyVariables', BodyVariablesOf<TEndpoint>>;

type OptionalProperty<TKey extends string, TValue> = IsEmptyVariables<TValue> extends true
  ? { [K in TKey]?: never }
  : undefined extends TValue
    ? { [K in TKey]?: TValue }
    : { [K in TKey]: TValue };

type IsEmptyVariables<TValue> = keyof TValue extends never
  ? true
  : TValue extends Record<string, never>
    ? true
    : false;

/**
 * Sends typed requests to one generated API endpoint.
 */
export interface SwaggerEndpointClient<TEndpoint extends AnyApiEndpoint> {
  /**
   * Sends a typed request for the configured endpoint.
   *
   * @param variables The path, query, header, and body variables for the endpoint.
   * @returns A promise of the endpoint response type.
   * @throws SwaggerHttpError when the HTTP response status is not successful.
   */
  request(variables?: SwaggerRequestVariables<TEndpoint>): Promise<ResponseOf<TEndpoint>>;
}

/**
 * Creates a memoized typed client for a generated API endpoint.
 *
 * @param endpoint The generated endpoint definition to call.
 * @param config The swagger client runtime configuration.
 * @returns A typed endpoint client.
 */
export function useSwaggerClient<TEndpoint extends AnyApiEndpoint>(
  endpoint: TEndpoint,
  config: SwaggerClientConfig
): SwaggerEndpointClient<TEndpoint> {
  return useMemo(() => createSwaggerClient(endpoint, config), [endpoint, config]);
}

/**
 * Creates a typed client for a generated API endpoint.
 *
 * @param endpoint The generated endpoint definition to call.
 * @param config The swagger client runtime configuration.
 * @returns A typed endpoint client.
 */
export function createSwaggerClient<TEndpoint extends AnyApiEndpoint>(
  endpoint: TEndpoint,
  config: SwaggerClientConfig
): SwaggerEndpointClient<TEndpoint> {
  return {
    async request(variables?: SwaggerRequestVariables<TEndpoint>): Promise<ResponseOf<TEndpoint>> {
      const fetchImpl = config.fetch ?? globalThis.fetch;
      const request = buildRequest(config, endpoint, variables);
      const response = await fetchImpl(request.url, request.init);

      if (!response.ok) {
        throw new SwaggerHttpError(response);
      }

      if (response.status === 204) {
        return undefined as ResponseOf<TEndpoint>;
      }

      return await response.json() as ResponseOf<TEndpoint>;
    }
  };
}

/**
 * Represents a failed HTTP response from the generated React swagger client.
 */
export class SwaggerHttpError extends Error {
  /**
   * Creates an error for a failed HTTP response.
   *
   * @param response The failed fetch response.
   */
  constructor(readonly response: Response) {
    super('Swagger request failed with status ' + response.status + '.');
  }
}

function buildRequest<TEndpoint extends AnyApiEndpoint>(
  config: SwaggerClientConfig,
  endpoint: TEndpoint,
  variables?: SwaggerRequestVariables<TEndpoint>
): { url: string; init: RequestInit } {
  const pathVariables = variables?.pathVariables as Record<string, unknown> | undefined;
  const queryVariables = variables?.queryVariables as Record<string, unknown> | undefined;
  const headerVariables = variables?.headerVariables as Record<string, unknown> | undefined;
  const bodyVariables = variables?.bodyVariables;
  const path = endpoint.path.replace(/\{([^}]+)\}/g, (_, key: string) => {
    const value = pathVariables?.[key];

    if (value === undefined || value === null) {
      throw new Error('Missing path variable "' + key + '" for endpoint "' + endpoint.name + '".');
    }

    return encodeURIComponent(String(value));
  });
  const url = new URL(joinUrl(config.baseUrl, path));

  for (const [key, value] of Object.entries(queryVariables ?? {})) {
    if (value === undefined || value === null) {
      continue;
    }

    if (Array.isArray(value)) {
      for (const item of value) {
        url.searchParams.append(key, String(item));
      }
    } else {
      url.searchParams.set(key, String(value));
    }
  }

  const headers = {
    ...config.headers,
    ...stringifyRecord(headerVariables)
  };

  if (bodyVariables !== undefined) {
    headers['content-type'] ??= 'application/json';
  }

  return {
    url: url.toString(),
    init: {
      method: endpoint.method,
      headers,
      body: bodyVariables === undefined ? undefined : JSON.stringify(bodyVariables)
    }
  };
}

function stringifyRecord(record: Record<string, unknown> | undefined): Record<string, string> | undefined {
  if (!record) {
    return undefined;
  }

  return Object.fromEntries(
    Object.entries(record)
      .filter(([, value]) => value !== undefined && value !== null)
      .map(([key, value]) => [key, String(value)])
  );
}

function joinUrl(baseUrl: string, path: string): string {
  return baseUrl.replace(/\/+$/, '') + '/' + path.replace(/^\/+/, '');
}
`;
}
